jobs:
    assets_unit_tests:
        docker:
            - image: alpine/git
        steps:
            - run:
                  name: Success
                  command: echo "Assets tests OK"

    assets_integration_tests:
        machine:
            image: ubuntu-2004:202010-01
        resource_class: small
        steps:
            - run:
                  name: Success
                  command: echo "Assets tests OK"

version: 2.1
workflows:
    version: 2

    serenity:
        jobs:
            - assets_unit_tests:
                  requires:
                      - build_serenity
            - assets_integration_tests:
                  requires:
                      - build_serenity
            - feature_success:
                  name: asset_success
                  requires:
                      - assets_integration_tests
                      - assets_unit_tests
