jobs:
    unit_tests_dqi:
        docker:
            - image: alpine/git
        steps:
            - run:
                  name: Success
                  command: echo "DQI unit tests OK"

    all_tests_dqi:
        docker:
            - image: alpine/git
        steps:
            - run:
                  name: Success
                  command: echo "<< pipeline.parameters.scheduled-workflow >> DQI all"
