jobs:
    ref_entities_back:
        docker:
            - image: alpine/git
        steps:
            - run:
                  name: Success
                  command: echo "Ref entity unit tests OK"

    ref_entities_front:
        docker:
            - image: alpine/git
        steps:
            - run:
                  name: Success
                  command: echo "Ref entity ALL tests OK"
