parameters:
    scheduled-workflow:
        type: string
        default: "not_scheduled"

workflows:
    version: 2

    growth_edition_nightly:
        when:
            equal: [ "growth_edition_nightly", << pipeline.parameters.scheduled-workflow >> ]
        jobs:
            - deploy_growth_edition
