version: 2.1
workflows:
    version: 2

    raccoon_workflow:
        jobs:
            - launch_raccoon?:
                  type: approval
                  filters:
                      branches:
                          only:
                              - /raccoon.*/

            - assets_unit_tests:
                requires:
                    - launch_raccoon?
            - feature_success:
                requires:
                    - assets_unit_tests
