version: 2.1
workflows:
    version: 2

    raccoon_workflow:
        jobs:
            - all_tests_assets:
                filters:
                    branches:
                      only:
                          - /raccoon.*/
            - pull_request_success:
                requires:
                    - all_tests_assets
