version: 2.1
workflows:
    version: 2

    raccoon_workflow:
        jobs:
            - launch_raccoon?:
                  type: approval
                  filters:
                      branches:
                          only:
                              - /raccoon.*/

            - all_tests_assets:
                requires:
                    - launch_raccoon?
            - pull_request_success:
                requires:
                    - all_tests_assets
