version: 2.1
workflows:
    version: 2

    weasels_workflow:
#        when:
#            matches:
#                pattern: "^tst.+$"
#                value: << pipeline.git.branch >>
        jobs:
            - launch_weasel?:
                  type: approval
                  filters:
                      branches:
                          only:
                              - /weasel.*/
            - dqi_tests:
                  requires:
                      - launch_weasel?
            - feature_success:
                  requires:
                      - dqi_tests
